### PR TITLE
Same height for the image and the text in the PostCard

### PR DESCRIPTION
**Pull request by alexandernst**

### CODE REVIEW

**Comment by alexandernst** [comment]
@z3by This PR makes the image's height to be the same as the summary text.

Post___Develatio_s_Blog


The image ratio is preserved no matter the length of the text:

Post___Develatio_s_Blog

**Comment by z3by** [comment]
This looks odd if you use a non-white background image.

Screen Shot 2020-05-17 at 6 57 48 AM

**Comment by alexandernst** [comment]
Hmmm 🤔  Indeede. Maybe I should add some padding? Or maybe round the edges? What is your take on this?

**Comment by z3by** [comment]
I think we need to revert this PR.

**Pull request merged**
