### PR TITLE
Implement UI localization support

### PR DESCRIPTION
**Pull request by alexandernst**

### CODE REVIEW

**Comment by alexandernst** [comment]
@z3by ping me if you want me to add anything

**Comment by z3by** [comment]
Could we support more than one language?

**Comment by alexandernst** [comment]
@z3by Like a language selector in the header?

**Comment by z3by** [comment]
I was planning to add support for different languages, but it seems a time-consuming task.

**Comment by alexandernst** [comment]
IMHO that is something entirely different. This MR is just about localising the UI, and I guess you're thinking in supporting multiple languages for the posts. Is that correct?

**Comment by z3by** [comment]
I am thinking about the posts and the UI as well.

**Comment by z3by** [comment]
This is now beyond my scope, don't worry about it.

**Pull request merged**
